# To create and activate the conda environment, run:
# - `conda env create -f environment.yml`; then
# - `conda activate face-sota`

name: face-sota
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pytorch=2.2.1
  - torchvision=0.17.1
  - cudatoolkit=12.1  # if no GPU or different version, you can remove or adjust this
  - numpy=1.26.4
  - scipy=1.12.0
  - pillow=10.2.0
  - matplotlib=3.8.3
  - scikit-learn=1.4.0
  - tqdm=4.66.2
  - opencv=4.9.0
  - seaborn=0.13.2
  - pip:
      - facenet-pytorch==2.6.0
      - insightface==0.7.3
      - umap-learn==0.5.5
      - git+https://github.com/mk-minchul/AdaFace.git